apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"activegate","app.kubernetes.io/name":"dynatrace-operator","app.kubernetes.io/version":"0.7.2"},"name":"dynatrace-kubernetes-monitoring"},"rules":[{"apiGroups":[""],"resources":["nodes","pods","namespaces","replicationcontrollers","events","resourcequotas","pods/proxy","nodes/proxy","services"],"verbs":["list","watch","get"]},{"apiGroups":["batch"],"resources":["jobs","cronjobs"],"verbs":["list","watch","get"]},{"apiGroups":["apps"],"resources":["deployments","replicasets","statefulsets","daemonsets"],"verbs":["list","watch","get"]},{"apiGroups":["apps.openshift.io"],"resources":["deploymentconfigs"],"verbs":["list","watch","get"]},{"apiGroups":["config.openshift.io"],"resources":["clusterversions"],"verbs":["list","watch","get"]},{"nonResourceURLs":["/metrics","/version","/readyz","/livez"],"verbs":["get"]}]}
  creationTimestamp: "2022-08-16T23:41:37Z"
  labels:
    app.kubernetes.io/component: activegate
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.7.2
  name: dynatrace-kubernetes-monitoring
  resourceVersion: "67944"
  uid: facbdf90-1f48-4710-bf2d-2c4adbea6c1b
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - namespaces
  - replicationcontrollers
  - events
  - resourcequotas
  - pods/proxy
  - nodes/proxy
  - services
  - nodes/metrics
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - list
  - watch
  - get
- nonResourceURLs:
  - /metrics
  - /version
  - /readyz
  - /livez
  verbs:
  - get
